sonar.projectKey=milos85vasic_My-Patreon-Manager
sonar.organization=milos85vasic
sonar.projectName=My Patreon Manager
sonar.projectVersion=0.1.0

sonar.sources=cmd,internal
sonar.tests=tests,internal
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/testdata/**,**/*.pb.go,**/mocks/**,scripts/coverdiff/**

sonar.go.coverage.reportPaths=coverage/coverage.out
sonar.go.tests.reportPaths=coverage/test-report.out
sonar.go.golangci-lint.reportPaths=coverage/golangci-lint.out

sonar.sourceEncoding=UTF-8
